#!/bin/sh

curr_desktop=$(wmctrl -d | awk '{ if ($2 == "'*'") print $1}')
num_desk=$(wmctrl -d | wc -l)

function next {
    next_dt=$(echo "($curr_desktop + 1) % $num_desk" | bc)
    echo "$next_dt"
}

function prev {
    prev_dt=$(echo "($curr_desktop + $num_desk - 1) % $num_desk" | bc)
    echo "$prev_dt"
}

if [ $# -eq 1 ] ; then
    case $1 in
        "--next" )
            wmctrl -s $(next) ;;
        "--prev" )
            wmctrl -s $(prev) ;;
        "--wn-next" )
            wmctrl -r :ACTIVE: -t $(next) ; wmctrl -s $(next) ;;
        "--wn-prev" )
            wmctrl -r :ACTIVE: -t $(prev) ; wmctrl -s $(prev) ;;
    esac
else
    echo "Usage: desktops [--next|--prev]"
fi

