#!/bin/bash
# vim:foldmethod=marker


# ============ ONEDRIVE ================= {{{
function odstart {
    killall onedrive || true
    bash ~/.config/onedrive/starter
    ps -fC onedrive
}

function odsync {
    $HOME/Documents/scripts/onedrive/sync
    ps -fC onedrive
}
# }}}

function ssh-forget {
    if [ $# -ne 1 ] ; then
        echo "Forgets an ssh host from known_hosts"
        echo "Usage ssh-forget <hostname"
        return 1
    fi

    sed -i.bak "/^$1/d" ${HOME}/.ssh/known_hosts
}

function bat_pw {
    # read battery power consumption
    if [ $# -eq 0 ] ; then
        bat="BAT0"
    else
        bat=$1
    fi
    curr=$(cat /sys/class/power_supply/$bat/current_now)
    volt=$(cat /sys/class/power_supply/$bat/voltage_now)
    str="scale=2; $curr * $volt / 10^12"
    watt=$(echo "$str" | bc -l)
    echo "$watt W"
}

# add ssh identity to ssh-agent for seamless push/pull
function addsshkey {
    # if ssh-agent not running, start it
    ssh-add -l &>/dev/null
    if [ "$?" == 2 ]; then
        echo "Starting ssh agent"
        eval $(ssh-agent)
    else
        echo "ssh agent running"
    fi

    ssh-add ~/.ssh/id_rsa
}

function date_cmd {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "date"
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "gdate"
    fi
}

# convert millisecond timestamp into real date
function ts2date {
    ts=$1
    if (( $ts > 9999999999 )) ; then
        ts=$( echo "($ts + 500) / 1000" | bc )
    fi

    $(date_cmd) -d @$ts
}

# convert date and time to epoch timestamp
function date2ts {
    ts=$($(date_cmd) --date="$1" +"%s")
    echo "$ts * 1000" | bc
}

# =============== MUSIC STUFF ================ {{{
function ytdl {
    # Options explanation:
    # -c = continue interrupted
    # -i = ignore errors
    # -w = do not overwrite
    # -o = set title format
    # -x = extract audio
    # -a = read urls from file

    if [ -f $1 ] ; then
        opt="-a"
    else
        opt=""
    fi
    youtube-dl -ciwx --audio-format m4a -o '%(title)s.%(ext)s' $opt $1
    kid3 .
}
# }}}

