#!/bin/sh

reader=okular
editor=nvim

function view {
    if [[ ! -f $1.pdf ]]; then
        echo "File does not exist: $1.pdf"
        return 1
    fi
    
    make all
    $reader $1.pdf &
}

function new {
    if [[ -f $1.md ]]; then
        echo "File already exists: $1.md"
        return 1
    fi

    cp template.md $1.md
    $editor $1.md
}

function edit {
    # edit an existing note while viewing in a reader
    if [[ ! -f $1.md ]]; then
        echo "File does not exist: $1.md"
        return 1
    fi

    make all

    # start reader and remember the pid
    $reader $1.pdf &
    pid=$!

    # open editor
    $editor $1.md

    # when that's done, kill reader as well
    kill $pid

    # make all when done
    make all
}

