#!/bin/sh

reader=okular
editor=nvim

function arch {
    if [[ ! -f $1.md ]]; then
        echo "File does not exist: $1.md"
        return 1
    fi

    mv $1.* ./.archive
}

function view {
    if [[ ! -f $1.pdf ]]; then
        echo "File does not exist: $1.pdf"
        return 1
    fi
    
    make all
    $reader $1.pdf &
}

function new {
    if [[ -f $1.md ]]; then
        echo "File already exists: $1.md"
        return 1
    fi

    tmp=./.templates/template.md
    if [[ ! -z "$2" ]]; then
        tmp=./.templates/$2.md
    fi

    cp $tmp $1.md
    edit $1
}

function edit {
    # edit an existing note while viewing in a reader
    if [[ ! -f $1.md ]]; then
        echo "File does not exist: $1.md"
        return 1
    fi

    make all

    # start reader and remember the pid
    $reader $1.pdf &
    pid=$!

    # open editor
    $editor $1.md

    # when that's done, kill reader as well
    kill $pid

    # make all when done
    make all
}

