#!/bin/bash

synclient VertScrollDelta=-130
synclient HorizScrollDelta=-130
synclient TapButton1=1 TapButton2=3 TapButton3=2
synclient AccelFactor=0.10
synclient MaxSpeed=4.0 MinSpeed=0.3
xinput set-prop "DELL086F:00 06CB:7E92 Touchpad" "Synaptics Noise Cancellation" 1 1

