#!/bin/bash

synclient VertScrollDelta=-80
synclient HorizScrollDelta=-80
synclient TapButton1=1 TapButton2=3 TapButton3=2
synclient AccelFactor=0.10
synclient MaxSpeed=1.6 MinSpeed=0.1
xinput set-prop "DELL086F:00 06CB:7E92 Touchpad" "Synaptics Noise Cancellation" 1 1

