#!/bin/bash

logdir=$HOME/.log/onedrive

printf "\n$(date)\n" >> $logdir/personal/log
printf "\n$(date)\n" >> $logdir/uni/log

onedrive --synchronize --confdir="$HOME/.config/onedrive/personal" >> $logdir/personal/log &
onedrive --synchronize --confdir="$HOME/.config/onedrive/uni" >> $logdir/uni/log &

